sudo: required
services:
- docker
before_install:
- openssl aes-256-cbc -K $encrypted_81d8c0bb3f6f_key -iv $encrypted_81d8c0bb3f6f_iv
  -in service-account.json.enc -out service-account.json -d
- curl https://sdk.cloud.google.com | bash > /dev/null;
- source $HOME/google-cloud-sdk/path.bash.inc
- gcloud components update kubectl
- gcloud auth activate-service-account --key-file service-account.json
- gcloud config set project multi-k8s-267119
- gcloud config set compute/zone us-central1-a
- gcloud container clusters get-credentials multi-cluster
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
- docker build -t adenijiazeez/react-test -f ./client/Dockerfile.dev ./client
script:
- 
dd:
- openssl aes-256-cbc -K $encrypted_81d8c0bb3f6f_key -iv $encrypted_81d8c0bb3f6f_iv
  -in service-account.json.enc -out service-account.json -d
