sudo: required
services:
  - docker
before_install:
  - openssl aes-256-cbc -K $encrypted_81d8c0bb3f6f_key -iv $encrypted_81d8c0bb3f6f_iv -in service-account.json.enc -out service-account.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json
  - gcloud config set project multi-k8s-267119
  - gcloud config set compute/zone us-central1-a
  - gcloud container clusters get-credentials multi-cluster
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push adenijiazeez/multi-client
  - docker push adenijiazeez/multi-nginx
  - docker push adenijiazeez/multi-server
  - docker push adenijiazeez/multi-worker
  