apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
      - name: client
        image: adenijiazeez/multi-client
        resources:
          limits:
            memory: "128Mi"
            cpu: "200m"
        ports:
        - name: client-port
          containerPort: 3000
        livenessProbe:
          httpGet:
            path: /
            port: client-port
          initialDelaySeconds: 15
          timeoutSeconds: 30
        readinessProbe:
          httpGet:
            path: /
            port: client-port
          initialDelaySeconds: 15
          timeoutSeconds: 30
