apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: server
  template:
    metadata:
      labels:
        component: server
    spec:
      containers:
      - name: server
        image: adenijiazeez/multi-server
        resources:
          limits:
            memory: "128Mi"
            cpu: "200m"
        ports:
        - name: server-port
          containerPort: 5000
        livenessProbe:
          httpGet:
            path: /
            port: server-port
          initialDelaySeconds: 15
          timeoutSeconds: 30
        readinessProbe:
          httpGet:
            path: /
            port: server-port
          initialDelaySeconds: 15
          timeoutSeconds: 30
        env:
          - name: REDIS_HOST
            value: redis-cluster-ip-service
          - name: REDIS_PORT
            value: '6379'
          - name: PGUSER
            value: postgres
          - name: PGHOST
            value: postgres-cluster-ip-service
          - name: PGDATABASE
            value: postgres
          - name: PGPORT
            value: '5432'
          - name: PGPASSWORD
            valueFrom:
              secretKeyRef:
                name: pgpassword
                key: PGPASSWORD
